sudo: false

language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

branches:
  only:
    - master

notifications:
  email: false

script:
  - mvn -q scalastyle:check test

after_success:
  - mvn clean
